The main repository is located at [[https://gitlab.otonokizaka.moe/Umi/til]]

* Today I Learned

Collection of small writeups from my daily learning.

This document is best edited with emacs [[https://orgmode.org/][org-mode]].

** Emacs
*** Insert heading in org-mode

There are commands for inserting a heading below the current line in org-mode, so you don't have to type out the ~*~ yourself.

The most useful one is probably ~org-insert-heading-respect-content~, which inserts a new heading at the end of the current subtree.

[[https://orgmode.org/manual/Structure-Editing.html][h/t]]

** Python
*** Libffi error

When the underlying system upgrades ~libffi~, and you are using a Python version installed with ~pyenv~, you might run into this error:

#+begin_src python
>>> import ctypes
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/umi/.pyenv/versions/3.8.1/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
#+end_src

The reason is that ~libffi.so.6~ no longer exists and is repalced by a newer version of ~libffi~

The fix is simply recompile your Python:

#+begin_src shell
pyenv install -f 3.8.1 # or whatever version
#+end_src

** Vim
*** Fix indentation
The shortcut to fix code indentation in vim is ~=~.

You can use visual mode to select a block of code and use ~=~ to fix indentation for that selection.

You can also use ~=G~ to fix indentation for every line below the cursor.

[[https://dev.to/ka11away/7-vim-tips-that-changed-my-life-with-demo-51hg][h/t]]

*** Resize windows automatically

~CTRL+w =~

[[https://dev.to/ka11away/7-vim-tips-that-changed-my-life-with-demo-51hg][h/t]]
